version: "3.8"

services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    environment:
      - CSVSERVER_BORDER=Orange
    volumes:
      - ./inputdata:/csvserver/inputdata
    ports:
      - "9300:9300"

  prometheus:
    image: prom/prometheus:v2.45.2
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
