version: "3.8"

services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    ports:
      - "9300:9300"
    volumes:
      - ./inputdata:/csvserver/inputdata
    env_file:
      - csvserver.env
